.TH WMLJ 1 "December 30, 2001"
.SH NAME
wmlj \- a LiveJournal.com monitor for WindowMaker
.SH SYNOPSIS
.B wmlj
.SH DESCRIPTION
.B
wmlj
monitors your Friends List at LiveJournal.com, an online journaling
service. It's designed to sit at your WindowMaker dock panel. It
checks the Friends List for updates every given time interval, and if
some of your friends post new entries, it signals you with a neat
graphic animation sequence.
.SH USAGE
.TP
.B <Left mouse button, double-click>
If there are new posts (animation is active), reset the monitor and bring up your web browser of choice with your Friends List. If there are no new posts, run your LiveJournal client of choice (normally, LogJam).
.TP
.B <Right mouse button>
Pop-up menu.
.PP
Of course, you need a valid LiveJournal.com account in order to use
this program.
.SH CONFIGURATION
The program maintains a configuration file, $(HOME)/.wmljrc. However,
.BR wmlj "(" 1 ")"
is fully configurable via built-in settings dialog.
.SH SEE ALSO
.BR wmaker "(" 1 "),"
.BR logjam "(" 1 ")."
.PP
.UR http://wmlj.sourceforge.net/
http://wmlj.sourceforge.net/
.UE
.br
.UR http://www.livejournal.com/
http://www.livejournal.com/
.UE
.SH AUTHOR
Sergei Barbarash <sgt@livejournal.com>
